/*
Converts a single asset into another asset

This is a "clean" conversion i.e. does not involve markups, fees, etc.
Uses the "official market" rate where it could be argued that there was no profit or loss generated by doing the conversion.

Uses the typical structure of:

- Asset "pair"
- Different rates for "buy" and "sell"

Example:

xxxxxx
xxxxxx

*/






// -------------------
// Fetch the official market rate

// Asset "pair" (asset 1 and asset 2)

// Use "buy" or "sell" rate?
